In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2

In [5]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)

In [7]:
y.grad_fn # 関数を保持しているアドレスの表示

In [8]:
z = y * y * 3

In [9]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)

In [10]:
out = z.mean() # zの値の平均

In [11]:
out

tensor(27., grad_fn=<MeanBackward1>)

In [12]:
a = torch.randn(2, 2) 

In [13]:
a

tensor([[ 1.7935,  0.9358],
        [ 0.5543, -0.2042]])

In [14]:
a.requires_grad

False

In [15]:
a.requires_grad_(True) # フラグを反転

tensor([[ 1.7935,  0.9358],
        [ 0.5543, -0.2042]], requires_grad=True)

In [18]:
a.requires_grad

True

In [19]:
b = (a * a).sum()

In [20]:
b

tensor(4.4415, grad_fn=<SumBackward0>)

In [21]:
b.grad_fn # 生成する関数の保持を確認

## backward()で微分地を求める

In [22]:
out.backward()

In [23]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])