In [1]:
import torch


In [3]:
x = torch.empty(5, 3) # ランダム多次元行列，値の初期化なし
print(x)

tensor([[1.7258e-09, 1.2747e-09, 2.0556e+12],
        [1.3765e-09, 1.4202e-09, 3.0281e+22],
        [1.0645e-09, 7.5739e-10, 7.8919e+16],
        [8.4149e-10, 9.2473e-10, 1.0709e-09],
        [7.8285e-10, 4.7362e-10, 0.0000e+00]])


In [28]:
x = torch.rand(5, 3) # ０～１の乱数

In [29]:
print(x)

tensor([[0.4209, 0.9427, 0.4759],
        [0.5908, 0.4584, 0.0048],
        [0.5124, 0.1187, 0.0227],
        [0.4465, 0.2492, 0.1913],
        [0.9289, 0.0982, 0.0968]])


In [30]:
x = torch.zeros(5, 3, dtype=torch.long) # 0で初期化

In [31]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [32]:
x = torch.tensor([5.5, 3]) # 初期値を与えて初期化

In [33]:
print(x)

tensor([5.5000, 3.0000])


In [34]:
x = x.new_ones(5, 3, dtype=torch.double) # 既存のｘを上書き→１

In [35]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [36]:
x = torch.randn_like(x, dtype=torch.float) # 平均が０・分散が１，形状の継承

In [37]:
print(x)

tensor([[-0.8610, -1.3380, -1.2164],
        [ 1.2379,  1.5194, -0.4433],
        [-1.1132,  1.6477, -0.8957],
        [ 0.3278,  0.3127,  0.2193],
        [ 0.3970, -0.8661, -0.4189]])


In [38]:
x.size() # サイズの確認

torch.Size([5, 3])

## テンソルの演算

In [39]:
y = torch.rand(5, 3)

In [40]:
print(y)

tensor([[0.1748, 0.6289, 0.2649],
        [0.7865, 0.6634, 0.3182],
        [0.8645, 0.5234, 0.9600],
        [0.3588, 0.7115, 0.3188],
        [0.1321, 0.4898, 0.6536]])


In [41]:
x + y

tensor([[-0.6861, -0.7090, -0.9515],
        [ 2.0244,  2.1827, -0.1251],
        [-0.2487,  2.1711,  0.0643],
        [ 0.6865,  1.0241,  0.5381],
        [ 0.5291, -0.3763,  0.2347]])

In [42]:
torch.add(x, y)

tensor([[-0.6861, -0.7090, -0.9515],
        [ 2.0244,  2.1827, -0.1251],
        [-0.2487,  2.1711,  0.0643],
        [ 0.6865,  1.0241,  0.5381],
        [ 0.5291, -0.3763,  0.2347]])

In [43]:
result = torch.empty(5, 3)

In [44]:
result

tensor([[1.7258e-09, 1.2747e-09, 2.0556e+12],
        [1.3765e-09, 1.4202e-09, 3.0281e+22],
        [1.0645e-09, 7.5739e-10, 7.8919e+16],
        [8.4149e-10, 9.2473e-10, 1.0709e-09],
        [7.8285e-10, 4.7362e-10, 0.0000e+00]])

In [45]:
torch.add(x, y, out=result) # 計算結果で上書き，resultの値を表示

tensor([[-0.6861, -0.7090, -0.9515],
        [ 2.0244,  2.1827, -0.1251],
        [-0.2487,  2.1711,  0.0643],
        [ 0.6865,  1.0241,  0.5381],
        [ 0.5291, -0.3763,  0.2347]])

In [46]:
y.add_(x)

tensor([[-0.6861, -0.7090, -0.9515],
        [ 2.0244,  2.1827, -0.1251],
        [-0.2487,  2.1711,  0.0643],
        [ 0.6865,  1.0241,  0.5381],
        [ 0.5291, -0.3763,  0.2347]])

In [50]:
x[:, 1] ## スライス

tensor([-1.3380,  1.5194,  1.6477,  0.3127, -0.8661])

In [51]:
x

tensor([[-0.8610, -1.3380, -1.2164],
        [ 1.2379,  1.5194, -0.4433],
        [-1.1132,  1.6477, -0.8957],
        [ 0.3278,  0.3127,  0.2193],
        [ 0.3970, -0.8661, -0.4189]])

## Numpyとの連携

In [53]:
a = torch.ones(5)

In [54]:
a

tensor([1., 1., 1., 1., 1.])

In [55]:
b = a.numpy()

In [56]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [57]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [58]:
b # ｂの要素も更新

array([2., 2., 2., 2., 2.], dtype=float32)

### NumpyからTorch Tensorへ

In [52]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [46]:
b # ｂの要素も更新

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)